queue_rules: []
merge_protections_settings:
  reporting_method: check-runs

pull_request_rules:
  - name: Automatically rebase outdated PRs
    conditions:
      - -conflict
      - base=main
    actions:
      rebase:
        bot_account: simon-testaccount
  - name: hi
    conditions: []
    actions:
      comment:
        message: |
          hello {{ cycler }} __init__ hello cycler.__init__
