on: pull_request_target

# checkout head_ref
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        run: |
          echo ${{ github.actor }}"
          echo ${{ github.event.pull_request.user.login }}"