on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: |
          echo "${{ github.event.workflow_run.head_branch }}"